services:
  db:
    image: postgres:16-alpine
    container_name: barbearia_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: barbershop
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barbershop_db
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  mailpit:
    image: axllent/mailpit:latest
    container_name: barbearia_mailpit
    restart: unless-stopped
    ports:
      - "${MAILPIT_SMTP_PORT:-1025}:1025" # SMTP
      - "${MAILPIT_UI_PORT:-8025}:8025" # Web UI

volumes:
  db_data:
